# Generated by Django 4.2.7 on 2025-12-08 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('beta_health', 'Beta Health'), ('ehr', 'EHR'), ('emergency_service', 'Emergency Service')], max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('test_tenant_id', models.CharField(max_length=255)),
                ('prod_tenant_id', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('generic', 'Generic Email'), ('password_reset', 'Password Reset'), ('forgot_password', 'Forgot Password'), ('verification', 'Email Verification')], max_length=50)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('environment', models.CharField(choices=[('test', 'Test'), ('prod', 'Production')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('brevo_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='auth_service.product')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'db_table': 'email_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='email_logs_created_554a66_idx'), models.Index(fields=['product', 'email_type'], name='email_logs_product_58f352_idx'), models.Index(fields=['status'], name='email_logs_status_e3be55_idx')],
            },
        ),
    ]
