# Generated by Django 4.2.7 on 2025-12-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('generic', 'Generic Email'), ('password_reset', 'Password Reset'), ('forgot_password', 'Forgot Password'), ('verification', 'Email Verification'), ('welcome', 'Welcome Email')], max_length=50),
        ),
    ]
