# Generated by Django 4.2.7 on 2025-12-09 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0002_alter_emaillog_email_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailLog',
        ),
    ]
